# ~/.config/starship.toml - Prompt minimalista y rápido

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$docker_context\
$line_break\
$character"""

[username]
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style) "
show_always = false

[hostname]
ssh_only = true
format = "on [$hostname](bold yellow) "

[directory]
style = "bold cyan"
format = "in [$path]($style) "
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "🌱 "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "([\[$all_status$ahead_behind\]]($style) )"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = "🏳"
deleted = "🗑"
renamed = "📛"
modified = "📝"
staged = "🗃"
untracked = "🤷"

[nodejs]
symbol = "⬢ "
style = "bold green"
format = "via [$symbol($version )]($style)"

[docker_context]
symbol = "🐳 "
style = "blue bold"
format = "via [$symbol$context]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"

[line_break]
disabled = false

# Configuración de colores personalizados
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"