version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    
    volumes:
      # Código fuente
      - ..:/workspace:cached
      
      # Persistir node_modules para mejor performance
      - node_modules:/workspace/node_modules
      
      # Configuraciones de usuario
      - ~/.gitconfig:/home/node/.gitconfig:ro
      - ~/.ssh:/home/node/.ssh:ro
      
      # Cache de npm/pnpm
      - npm_cache:/home/node/.npm
      - pnpm_cache:/home/node/.local/share/pnpm
    
    ports:
      - "4321:4321"  # Astro dev server
      - "3000:3000"  # Preview server
    
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Para hot reload en algunos sistemas
    
    # Mantener el contenedor corriendo
    command: sleep infinity
    
    # Configuración de red
    networks:
      - dev_network

  # Servicio opcional para base de datos local (si se necesita)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: cubatattoostudio
  #     POSTGRES_USER: dev
  #     POSTGRES_PASSWORD: dev
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - dev_network

volumes:
  node_modules:
  npm_cache:
  pnpm_cache:
  # postgres_data:

networks:
  dev_network:
    driver: bridge