// @ts-nocheck
// This file is auto-generated by scripts/fetch-insta.js
// Do not edit manually

import img_studio_promo_flash from '../assets/gallery/studio/promo-flash.jpg';
import img_studio_promo_merch from '../assets/gallery/studio/promo-merch.jpg';
import img_studio_promo_relg from '../assets/gallery/studio/promo-relg.jpg';
import img_studio_promo_walkins from '../assets/gallery/studio/promo-walkins.jpg';
import img_david_01 from '../assets/gallery/david/01.jpg';
import img_david_02 from '../assets/gallery/david/02.jpg';
import img_david_03 from '../assets/gallery/david/03.jpg';
import img_david_04 from '../assets/gallery/david/04.jpg';
import img_david_05 from '../assets/gallery/david/05.jpg';
import img_david_06 from '../assets/gallery/david/06.jpg';
import img_david_07 from '../assets/gallery/david/07.jpg';
import img_david_08 from '../assets/gallery/david/08.jpg';
import img_david_09 from '../assets/gallery/david/09.jpg';
import img_david_10 from '../assets/gallery/david/10.jpg';
import img_david_11 from '../assets/gallery/david/11.jpg';
import img_david_12 from '../assets/gallery/david/12.jpg';
import profile_david from '../assets/artists/david.jpg';
import img_nina_01 from '../assets/gallery/nina/01.jpg';
import img_nina_02 from '../assets/gallery/nina/02.jpg';
import img_nina_03 from '../assets/gallery/nina/03.jpg';
import img_nina_04 from '../assets/gallery/nina/04.jpg';
import img_nina_05 from '../assets/gallery/nina/05.jpg';
import img_nina_06 from '../assets/gallery/nina/06.jpg';
import img_nina_07 from '../assets/gallery/nina/07.jpg';
import img_nina_08 from '../assets/gallery/nina/08.jpg';
import img_nina_09 from '../assets/gallery/nina/09.jpg';
import img_nina_10 from '../assets/gallery/nina/10.jpg';
import img_nina_11 from '../assets/gallery/nina/11.jpg';
import img_nina_12 from '../assets/gallery/nina/12.jpg';
import profile_nina from '../assets/artists/nina.jpg';
import img_karli_01 from '../assets/gallery/karli/01.jpg';
import img_karli_02 from '../assets/gallery/karli/02.jpg';
import img_karli_03 from '../assets/gallery/karli/03.jpg';
import img_karli_04 from '../assets/gallery/karli/04.jpg';
import img_karli_05 from '../assets/gallery/karli/05.jpg';
import img_karli_06 from '../assets/gallery/karli/06.jpg';
import img_karli_07 from '../assets/gallery/karli/07.jpg';
import img_karli_08 from '../assets/gallery/karli/08.jpg';
import img_karli_09 from '../assets/gallery/karli/09.jpg';
import img_karli_10 from '../assets/gallery/karli/10.jpg';
import img_karli_11 from '../assets/gallery/karli/11.jpg';
import img_karli_12 from '../assets/gallery/karli/12.jpg';
import profile_karli from '../assets/artists/karli.jpg';

export interface Post {
  id: string;
  imageUrl: ImageMetadata | string;
  caption?: string;
  permalink?: string;
  artist?: string;
  isLocal?: boolean;
}

export interface ArtistData {
  profile: {
    username?: string;
    fullName?: string;
    localProfilePic?: ImageMetadata | string;
  } | null;
  posts: Post[];
}

export interface InstagramData {
  posts: Post[];
  studio?: { profile: ArtistData['profile']; posts: Post[] };
  artists?: Record<string, ArtistData>;
  lastFetched?: string;
}

const instagramData: InstagramData = {
  "posts": [
    {
      "id": "local-studio-0",
      "imageUrl": img_studio_promo_flash,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "local-studio-1",
      "imageUrl": img_studio_promo_merch,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "local-studio-2",
      "imageUrl": img_studio_promo_relg,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "local-studio-3",
      "imageUrl": img_studio_promo_walkins,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "local-david-0",
      "imageUrl": img_david_01,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-1",
      "imageUrl": img_david_02,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-2",
      "imageUrl": img_david_03,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-3",
      "imageUrl": img_david_04,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-4",
      "imageUrl": img_david_05,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-5",
      "imageUrl": img_david_06,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-6",
      "imageUrl": img_david_07,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-7",
      "imageUrl": img_david_08,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-8",
      "imageUrl": img_david_09,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-9",
      "imageUrl": img_david_10,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-10",
      "imageUrl": img_david_11,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-11",
      "imageUrl": img_david_12,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-nina-0",
      "imageUrl": img_nina_01,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-1",
      "imageUrl": img_nina_02,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-2",
      "imageUrl": img_nina_03,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-3",
      "imageUrl": img_nina_04,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-4",
      "imageUrl": img_nina_05,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-5",
      "imageUrl": img_nina_06,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-6",
      "imageUrl": img_nina_07,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-7",
      "imageUrl": img_nina_08,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-8",
      "imageUrl": img_nina_09,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-9",
      "imageUrl": img_nina_10,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-10",
      "imageUrl": img_nina_11,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-11",
      "imageUrl": img_nina_12,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-karli-0",
      "imageUrl": img_karli_01,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-1",
      "imageUrl": img_karli_02,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-2",
      "imageUrl": img_karli_03,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-3",
      "imageUrl": img_karli_04,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-4",
      "imageUrl": img_karli_05,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-5",
      "imageUrl": img_karli_06,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-6",
      "imageUrl": img_karli_07,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-7",
      "imageUrl": img_karli_08,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-8",
      "imageUrl": img_karli_09,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-9",
      "imageUrl": img_karli_10,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-10",
      "imageUrl": img_karli_11,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-11",
      "imageUrl": img_karli_12,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    }
  ],
  "studio": {
    "profile": null,
    "posts": [
      {
        "id": "local-studio-0",
        "imageUrl": img_studio_promo_flash,
        "caption": "Local fallback image",
        "permalink": "",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "local-studio-1",
        "imageUrl": img_studio_promo_merch,
        "caption": "Local fallback image",
        "permalink": "",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "local-studio-2",
        "imageUrl": img_studio_promo_relg,
        "caption": "Local fallback image",
        "permalink": "",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "local-studio-3",
        "imageUrl": img_studio_promo_walkins,
        "caption": "Local fallback image",
        "permalink": "",
        "artist": "studio",
        "isLocal": true
      }
    ]
  },
  "artists": {
    "david": {
      "profile": {
        "username": "david_fallback",
        "fullName": "david Fallback",
        "localProfilePic": profile_david
      },
      "posts": [
        {
          "id": "local-david-0",
          "imageUrl": img_david_01,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-1",
          "imageUrl": img_david_02,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-2",
          "imageUrl": img_david_03,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-3",
          "imageUrl": img_david_04,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-4",
          "imageUrl": img_david_05,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-5",
          "imageUrl": img_david_06,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-6",
          "imageUrl": img_david_07,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-7",
          "imageUrl": img_david_08,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-8",
          "imageUrl": img_david_09,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-9",
          "imageUrl": img_david_10,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-10",
          "imageUrl": img_david_11,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-11",
          "imageUrl": img_david_12,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        }
      ]
    },
    "nina": {
      "profile": {
        "username": "nina_fallback",
        "fullName": "nina Fallback",
        "localProfilePic": profile_nina
      },
      "posts": [
        {
          "id": "local-nina-0",
          "imageUrl": img_nina_01,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-1",
          "imageUrl": img_nina_02,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-2",
          "imageUrl": img_nina_03,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-3",
          "imageUrl": img_nina_04,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-4",
          "imageUrl": img_nina_05,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-5",
          "imageUrl": img_nina_06,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-6",
          "imageUrl": img_nina_07,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-7",
          "imageUrl": img_nina_08,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-8",
          "imageUrl": img_nina_09,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-9",
          "imageUrl": img_nina_10,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-10",
          "imageUrl": img_nina_11,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-11",
          "imageUrl": img_nina_12,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        }
      ]
    },
    "karli": {
      "profile": {
        "username": "karli_fallback",
        "fullName": "karli Fallback",
        "localProfilePic": profile_karli
      },
      "posts": [
        {
          "id": "local-karli-0",
          "imageUrl": img_karli_01,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-1",
          "imageUrl": img_karli_02,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-2",
          "imageUrl": img_karli_03,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-3",
          "imageUrl": img_karli_04,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-4",
          "imageUrl": img_karli_05,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-5",
          "imageUrl": img_karli_06,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-6",
          "imageUrl": img_karli_07,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-7",
          "imageUrl": img_karli_08,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-8",
          "imageUrl": img_karli_09,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-9",
          "imageUrl": img_karli_10,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-10",
          "imageUrl": img_karli_11,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-11",
          "imageUrl": img_karli_12,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        }
      ]
    }
  },
  "lastFetched": "2026-02-26T19:47:42.452Z"
};

export default instagramData;
