// @ts-nocheck
// This file is auto-generated by scripts/fetch-insta.js
// Do not edit manually

import profile_studio from '../assets/artists/studio.jpg';
import profile_david from '../assets/artists/david.jpg';
import profile_nina from '../assets/artists/nina.jpg';
import profile_karli from '../assets/artists/karli.jpg';
import img_studio_01 from '../assets/gallery/studio/01.jpg';
import img_studio_02 from '../assets/gallery/studio/02.jpg';
import img_studio_03 from '../assets/gallery/studio/03.jpg';
import img_studio_04 from '../assets/gallery/studio/04.jpg';
import img_studio_05 from '../assets/gallery/studio/05.jpg';
import img_studio_06 from '../assets/gallery/studio/06.jpg';
import img_studio_07 from '../assets/gallery/studio/07.jpg';
import img_studio_08 from '../assets/gallery/studio/08.jpg';
import img_studio_09 from '../assets/gallery/studio/09.jpg';
import img_studio_10 from '../assets/gallery/studio/10.jpg';
import img_studio_11 from '../assets/gallery/studio/11.jpg';
import img_studio_12 from '../assets/gallery/studio/12.jpg';
import img_david_01 from '../assets/gallery/david/01.jpg';
import img_david_02 from '../assets/gallery/david/02.jpg';
import img_david_03 from '../assets/gallery/david/03.jpg';
import img_david_04 from '../assets/gallery/david/04.jpg';
import img_david_05 from '../assets/gallery/david/05.jpg';
import img_david_06 from '../assets/gallery/david/06.jpg';
import img_david_07 from '../assets/gallery/david/07.jpg';
import img_david_08 from '../assets/gallery/david/08.jpg';
import img_david_09 from '../assets/gallery/david/09.jpg';
import img_david_10 from '../assets/gallery/david/10.jpg';
import img_david_11 from '../assets/gallery/david/11.jpg';
import img_david_12 from '../assets/gallery/david/12.jpg';
import img_nina_01 from '../assets/gallery/nina/01.jpg';
import img_nina_02 from '../assets/gallery/nina/02.jpg';
import img_nina_03 from '../assets/gallery/nina/03.jpg';
import img_nina_04 from '../assets/gallery/nina/04.jpg';
import img_nina_05 from '../assets/gallery/nina/05.jpg';
import img_nina_06 from '../assets/gallery/nina/06.jpg';
import img_nina_07 from '../assets/gallery/nina/07.jpg';
import img_nina_08 from '../assets/gallery/nina/08.jpg';
import img_nina_09 from '../assets/gallery/nina/09.jpg';
import img_nina_10 from '../assets/gallery/nina/10.jpg';
import img_nina_11 from '../assets/gallery/nina/11.jpg';
import img_nina_12 from '../assets/gallery/nina/12.jpg';
import img_karli_01 from '../assets/gallery/karli/01.jpg';
import img_karli_02 from '../assets/gallery/karli/02.jpg';
import img_karli_03 from '../assets/gallery/karli/03.jpg';
import img_karli_04 from '../assets/gallery/karli/04.jpg';
import img_karli_05 from '../assets/gallery/karli/05.jpg';
import img_karli_06 from '../assets/gallery/karli/06.jpg';
import img_karli_07 from '../assets/gallery/karli/07.jpg';
import img_karli_08 from '../assets/gallery/karli/08.jpg';
import img_karli_09 from '../assets/gallery/karli/09.jpg';
import img_karli_10 from '../assets/gallery/karli/10.jpg';
import img_karli_11 from '../assets/gallery/karli/11.jpg';
import img_karli_12 from '../assets/gallery/karli/12.jpg';

export interface Post {
  id: string;
  imageUrl: ImageMetadata | string;
  caption?: string;
  permalink?: string;
  artist?: string;
  isLocal?: boolean;
}

export interface ArtistData {
  profile: {
    username?: string;
    fullName?: string;
    localProfilePic?: ImageMetadata | string;
  } | null;
  posts: Post[];
}

export interface InstagramData {
  posts: Post[];
  studio?: { profile: ArtistData['profile']; posts: Post[] };
  artists?: Record<string, ArtistData>;
  lastFetched?: string;
}

const instagramData: InstagramData = {
  "posts": [
    {
      "id": "3765029695869102410",
      "imageUrl": img_studio_01,
      "caption": "Some tattoos are more than designs — they’re balance, energy, and connection.\nMandalas remind me that every detail has a purpose. 🌿  If you have thought about getting one, maybe this is your sign ✨\n\n#mandalatattoo #dotworktattoo #ornamentaltattoo #goodnina #ninaromeroink #tattooart #tattooartist #blackwork #artonthebody #tattoolover #tatuadora",
      "permalink": "https://www.instagram.com/p/DRAEo93EylK/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3790511475068585170",
      "imageUrl": img_studio_02,
      "caption": "Every color, every shadow, and every choice in this design has intention behind it.\nThis is more than a tattoo — it’s a story built on skin, with emotion, strength, and depth.\nPieces like this are born from trust, communication, and a clear artistic vision from the very first line.\n\nIf you have a unique idea and want to turn it into real art, now is the time.\n📩 Book your appointment and let’s create something made just for you.\n\n📍 @cubatattoostudio \n#tattoo #tattooartistmagazine #tattoofullcolor #tatuaje #abq",
      "permalink": "https://www.instagram.com/p/DSamhqEgUTS/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3701331489341104159",
      "imageUrl": img_studio_03,
      "caption": "Un diseño poderoso, lleno de personalidad, representa tenacidad, fuerza y valor.\nQué esperas para agendar con nosotros en @cubatattoostudio y llevar en tu piel un diseño único? \n\nA powerful design, full of personality, represents tenacity, strength and courage.\nWhat are you waiting for to schedule with us at @cubatattoostudio and wear a unique design on your skin?\n\n#Zeus #Tatoo #GriegoTattoo #ZeusTattoo #BlackAndGreyTattoo #ColorTattoo #realismo",
      "permalink": "https://www.instagram.com/p/DNdxWEKJOAf/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3846971193186746126",
      "imageUrl": img_studio_04,
      "caption": "Cover up 🌸\nAn old tattoo turned into something completely new.\nNow the question is… can you spot where the old tattoo was",
      "permalink": "https://www.instagram.com/p/DVjL-sHDn8O/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3846249838657229611",
      "imageUrl": img_studio_05,
      "caption": "🔥First session done. This powerful piece is just getting started. More to come\nBooking large scale projects. DM for appointments.",
      "permalink": "https://www.instagram.com/p/DVgn9mWkVMr/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3845819489375500307",
      "imageUrl": img_studio_06,
      "caption": "Small cover-up ✨\n\nSometimes all it takes is a little color to transform something that no longer represents you.\nThis was a small cover-up turned into a vibrant piece. 🎨\n\nMy books are open! If you have a tattoo you’d like to cover with something bold and colorful, feel free to send me a DM and we can talk about a design for you.\n\n📍 Albuquerque, NM\n\n#cubatattoostudio #colortattoo #fullcolortattoo #colortatooartist #coveruptattoo",
      "permalink": "https://www.instagram.com/p/DVfGHMWgDgT/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3845520958757278416",
      "imageUrl": img_studio_07,
      "caption": "In Mexican culture, many people believe in La Santa Muerte as a symbol of protection, faith, and guidance. This piece represents that devotion, mixed with time, luck, and life’s journey. 🖤⏳♠️",
      "permalink": "https://www.instagram.com/p/DVeCPADDBLQ/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3843656155277417588",
      "imageUrl": img_studio_08,
      "caption": "Although this piece steps a bit outside of my usual style, I truly enjoyed working on it.\nIt’s also part of the 30% off promotion we’re currently offering 🔥\n\nIf you’re thinking about something similar, now’s the time to take advantage.",
      "permalink": "https://www.instagram.com/p/DVXaOieDdx0/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3843597864592770207",
      "imageUrl": img_studio_09,
      "caption": "100% healed tattoo ✨\n\nThis is what a piece looks like when the process is respected and the instructions for subsequent care are correctly followed. The final result depends not only on the artist, but also on the customer’s commitment during healing.\n\nLittle reminder: aftercare is as important as the tattoo itself.",
      "permalink": "https://www.instagram.com/p/DVXM-TCgISf/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3842622245525633256",
      "imageUrl": img_studio_10,
      "caption": "Another powerful piece done under the 30% OFF Religious Tattoo Promotion 🙏\n\nMarch booking is officially open and the promo is still running.\nIf you’re planning something meaningful, now is the perfect time to start.\n\nLimited availability for March — lock in your spot before it’s gone.",
      "permalink": "https://www.instagram.com/p/DVTvJK-kbjo/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3841968206478686450",
      "imageUrl": img_studio_11,
      "caption": "Another piece from our extended March promotion 🔥\nEnjoy 30% OFF on religious tattoos all month long.\n\nMarch spots are filling fast — secure yours now and let’s bring your vision to life.\n\nBook your session before the remaining dates are gone.",
      "permalink": "https://www.instagram.com/p/DVRabppgbjy/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3841239444540546245",
      "imageUrl": img_studio_12,
      "caption": "Because so many people missed out this month, we’ve decided to extend our 30% OFF promotion on religious themed pieces through March 🙏\n\nFaith-inspired projects like this one are now eligible for the discount — giving more of you the chance to bring meaningful art to life.\n\nIf you were thinking about getting something spiritual done, this is your opportunity before spots fill again.\n\nLet me know what you’ve been wanting to create ✨",
      "permalink": "https://www.instagram.com/p/DVO0uxNDtzF/",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "3790511475068585170",
      "imageUrl": img_david_01,
      "caption": "Every color, every shadow, and every choice in this design has intention behind it.\nThis is more than a tattoo — it’s a story built on skin, with emotion, strength, and depth.\nPieces like this are born from trust, communication, and a clear artistic vision from the very first line.\n\nIf you have a unique idea and want to turn it into real art, now is the time.\n📩 Book your appointment and let’s create something made just for you.\n\n📍 @cubatattoostudio \n#tattoo #tattooartistmagazine #tattoofullcolor #tatuaje #abq",
      "permalink": "https://www.instagram.com/p/DSamhqEgUTS/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3752195299918071455",
      "imageUrl": img_david_02,
      "caption": "✨ Surreal Neon Vision ✨\n Work in progress 📌\nA bold mix of surrealism and futuristic realism, bringing this character to life through powerful neons, soft blends and dramatic contrasts.\nEvery detail is custom, every stroke has intention — art that lives on your skin.\n\nIf you want a unique surreal piece with this level of depth and color, I’m now booking new sessions. 🚀🖌️\n\n📍 @cubatattoostudio – Albuquerque, NM\n📲 DM to book your appointment\n\n#CubaTattooStudio #SurrealTattoo #ColorRealism #NeonTattoo #LegTattoo #TattooArtist #CustomTattoo #TattooArt #Inked #BookNow #RealisticTattoo #Colortattoo #SurrealismArt",
      "permalink": "https://www.instagram.com/p/DQSeb7Lgcaf/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3676888274027693491",
      "imageUrl": img_david_03,
      "caption": "🔥 Winner of “Best of Show - Color” at @newmexicotattoofiesta 2025 🔥\nThis piece was completed in just 9 hours — packed with texture, contrast, color, and soul.\nHuge thanks to everyone who supported me, and a special shoutout to @_poor_vida_ for the help and for giving us the chance to be part of this amazing event.\n\nThis is what we do at @cubatattoostudio — high-level art with full dedication.\nWe’re just getting started. Let’s keep raising the bar! 💪🏽🖤\n\n📍CUBA TATTOO STUDIO | Albuquerque, NM\n📅 Book your session now and bring your vision to life.\n\n#BestOfShow #TattooFiesta2025 #ColorTattoo #RealismTattoo #CubaTattooStudio #PoorVida #NewMexicoTattoos #TattooAward #TattooArtist #9HourTattoo #FullColorTattoo #TattooInspiration #AlbuquerqueTattoo #TattooLife",
      "permalink": "https://www.instagram.com/p/DMG7md8OEWz/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3846971193186746126",
      "imageUrl": img_david_04,
      "caption": "Cover up 🌸\nAn old tattoo turned into something completely new.\nNow the question is… can you spot where the old tattoo was",
      "permalink": "https://www.instagram.com/p/DVjL-sHDn8O/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3846249838657229611",
      "imageUrl": img_david_05,
      "caption": "🔥First session done. This powerful piece is just getting started. More to come\nBooking large scale projects. DM for appointments.",
      "permalink": "https://www.instagram.com/p/DVgn9mWkVMr/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3845520958757278416",
      "imageUrl": img_david_06,
      "caption": "In Mexican culture, many people believe in La Santa Muerte as a symbol of protection, faith, and guidance. This piece represents that devotion, mixed with time, luck, and life’s journey. 🖤⏳♠️",
      "permalink": "https://www.instagram.com/p/DVeCPADDBLQ/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3843656155277417588",
      "imageUrl": img_david_07,
      "caption": "Although this piece steps a bit outside of my usual style, I truly enjoyed working on it.\nIt’s also part of the 30% off promotion we’re currently offering 🔥\n\nIf you’re thinking about something similar, now’s the time to take advantage.",
      "permalink": "https://www.instagram.com/p/DVXaOieDdx0/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3842622245525633256",
      "imageUrl": img_david_08,
      "caption": "Another powerful piece done under the 30% OFF Religious Tattoo Promotion 🙏\n\nMarch booking is officially open and the promo is still running.\nIf you’re planning something meaningful, now is the perfect time to start.\n\nLimited availability for March — lock in your spot before it’s gone.",
      "permalink": "https://www.instagram.com/p/DVTvJK-kbjo/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3841968206478686450",
      "imageUrl": img_david_09,
      "caption": "Another piece from our extended March promotion 🔥\nEnjoy 30% OFF on religious tattoos all month long.\n\nMarch spots are filling fast — secure yours now and let’s bring your vision to life.\n\nBook your session before the remaining dates are gone.",
      "permalink": "https://www.instagram.com/p/DVRabppgbjy/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3841239444540546245",
      "imageUrl": img_david_10,
      "caption": "Because so many people missed out this month, we’ve decided to extend our 30% OFF promotion on religious themed pieces through March 🙏\n\nFaith-inspired projects like this one are now eligible for the discount — giving more of you the chance to bring meaningful art to life.\n\nIf you were thinking about getting something spiritual done, this is your opportunity before spots fill again.\n\nLet me know what you’ve been wanting to create ✨",
      "permalink": "https://www.instagram.com/p/DVO0uxNDtzF/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3840502269272484934",
      "imageUrl": img_david_11,
      "caption": "Faith, family, and purpose. 🙏\nThis piece is part of our 30% OFF promotion on religious-themed tattoos for this month.\n\nIf you’ve been thinking about representing your faith through art, this is the perfect time to make it happen.\n\n📍 @cubatattoostudio – Albuquerque, NM\n📩 Send us a DM to book your appointment before spots fill up.",
      "permalink": "https://www.instagram.com/p/DVMNHdPEWxG/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3839844037859327047",
      "imageUrl": img_david_12,
      "caption": "Faith turned into art ✝️🔥\nThis piece was part of our 30% OFF religious tattoo promotion this month.\nAll spots are now filled — but if you want me to continue this promotion next month, drop a comment below 👇",
      "permalink": "https://www.instagram.com/p/DVJ3c7dgbxH/",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "3789748958915404471",
      "imageUrl": img_nina_01,
      "caption": "Soft art for timeless skin 🌸\nFine line floral tattoo, created with intention and detail.\nSubtle, feminine, and meant to flow with the body.  By: @goodnina_tattooing  #abqtattooartist #abqtattoos #finelinetattoos #floraltattoo #tattoogi̇rl #newmexicotattoo #goodnina #tattoolover",
      "permalink": "https://www.instagram.com/p/DSX5JlkDyK3/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3780998917119924705",
      "imageUrl": img_nina_02,
      "caption": "Si te gustan las líneas finas, la simetría y los detalles elegantes, este estilo es perfecto para ti.\nEstoy abriendo agenda para más piezas como esta: personalizadas, delicadas y hechas a tu medida.\n\n💬 Envíame mensaje para cotizar tu diseño\n🖤 Trabajos limpios · Trazo fino · Estilo ornamental único  #tattooing #tattoo #tattooartists #tattoogirl #tattooornamental #geometrico #tattoolifestyle #tattooidea #tattooabq #tattooalburquerque #tattoonewmexico #tattooshop #tattoolover #tattoowork #goodnina",
      "permalink": "https://www.instagram.com/p/DR4znuHEdnh/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3844075245544772395",
      "imageUrl": img_nina_03,
      "caption": "A new chapter in red.\n\nThreads of Spring is now available throughout March.\nLimited booking spots each week.\n\nDM to claim your piece.\n#finelinetattoos #abqtattoos #femaletattoo #ornamentaltattoos #tattoo",
      "permalink": "https://www.instagram.com/p/DVY5hGskZMr/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3843307420081266953",
      "imageUrl": img_nina_04,
      "caption": "Tiny tattoos that stole my heart in February\n| love when something this small can hold so much meaning.\nDelicate lines, soft shading, tiny details... but big intention.\nFebruary was full of subtle pieces that whisper instead of scream tr\nAnd honestly? Those are my favorite kind.\nGracias por confiar en mí para llevar algo tan personal en la piel.\nMis tiny siempre tendrán un lugar especial.\nIf you’re thinking about a tiny piece... this is your sign.\n- Good Nina\n#tynitattoo #alburquerque #finelinetattoos #feminetattoo #newméxico",
      "permalink": "https://www.instagram.com/p/DVWK7xgkSEJ/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3841975692388548873",
      "imageUrl": img_nina_05,
      "caption": "Este diseño nació para fluir con el cuerpo.\nNo es solo un tatuaje, es una pieza que respira con cada curva. ⚜️\nEl tamaño puede adaptarse según zona.\nSi conectas con esta pieza, escríbeme para reservar.✨ #feminitattoo #ornamentaltattoo #abqtattooartist #newmex",
      "permalink": "https://www.instagram.com/p/DVRcIlcgUEJ/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3841153399509836708",
      "imageUrl": img_nina_06,
      "caption": "Flores de Febrero.  Creando un jardín. #tattooflowers #linetattoos #abq #abqtattooartist #tattoogirl",
      "permalink": "https://www.instagram.com/p/DVOhKphkWOk/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3837115455220334381",
      "imageUrl": img_nina_07,
      "caption": "Líneas que fluyen como energía.\nMandala en pura línea, trabajado con intención y precisión.\n\nAgenda abierta ✨\n#MandalaTattoo #LineworkTattoo #FineLineTattoo #CustomTattoo #TattooArtist",
      "permalink": "https://www.instagram.com/p/DVALC02kb8t/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3834861432593126195",
      "imageUrl": img_nina_08,
      "caption": "Este tatuaje es un recordatorio de cómo la magia sucede. In God’s Hands, las sorpresas son parte del camino. ❤️✨. #tattoo #abqtattoo #tattooartists #tattooidea #newmexicoart",
      "permalink": "https://www.instagram.com/p/DU4KiesjxMz/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3830274259437032141",
      "imageUrl": img_nina_09,
      "caption": "“Un mes después 🤍✨\nRetoque en el nombre y el resto del tatuaje ya curado.\nGracias por volver y confiar otra vez 🐾\nNada más lindo que ver cómo sana un tattoo con el tiempo.” #petlovers #petstattoo #abqtattoo #newméxico",
      "permalink": "https://www.instagram.com/p/DUn3iUyERLN/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3827683857697691570",
      "imageUrl": img_nina_10,
      "caption": "Hoy pasó algo muy especial ✨\nMi clienta confió en mí, en un dibujo que traía en mi libreta, y me dejó fluir en freehand.\nEl proceso fue intuitivo, orgánico… y el resultado nos enamoró a las dos.\nGracias @grisellgandarilla por confiar, así nacen los tatuajes con alma 🖤 #tattoo #fineline #escorpio♏️ #abqtattoo #tattooartists",
      "permalink": "https://www.instagram.com/p/DUeqjBKkVey/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3824716028602095130",
      "imageUrl": img_nina_11,
      "caption": "Recuerden que este viernes 13 de febrero tenemos ofertas especiales ✨\nPara solteros, parejas, novios, amigos, familia…\ny para todo el que sienta amor 🖤\nPorque el amor también se tatúa. #tattoo #finelinetattoos #tattooabq #tattooartist #valentinday❤️",
      "permalink": "https://www.instagram.com/p/DUUHva7khYa/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3823333901162526007",
      "imageUrl": img_nina_12,
      "caption": "Plot twist: el tatuaje no fue el protagonista…\nEllas frente a la cámara: 💃📸😂",
      "permalink": "https://www.instagram.com/p/DUPNe0cgDU3/",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "3762976379093203995",
      "imageUrl": img_karli_01,
      "caption": "Details, depth and a hypnotizing look. This tattoo was worked to create a piece with visual strength from any angle, soft shading, marked textures and those incandescent tones that give it life.\n\nBooks open for custom designs like this.\n\nIf you want something unique, made for you, send me a DM and we’ll plan it.\n\nTatuado por: Karlii Castillo\n📍 Cuba Tattoo Studio – Albuquerque, NM\n\n#AgendaAbierta #CubaTattooStudio #AlbuquerqueTattoo #AlbuquerqueArtist #TattooABQ #Realismo #RealismTattoo #BlackAndGreyTattoo #DarkArtTattoo #InkLife #TattooCollector #TatuajesFineline #TatuajeRealista #CustomTattoo #SkinArt #TattooStudio #BookNow #TattooDesign #MedusaTattoo",
      "permalink": "https://www.instagram.com/p/DQ4xxRmCTwb/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3701331489341104159",
      "imageUrl": img_karli_02,
      "caption": "Un diseño poderoso, lleno de personalidad, representa tenacidad, fuerza y valor.\nQué esperas para agendar con nosotros en @cubatattoostudio y llevar en tu piel un diseño único? \n\nA powerful design, full of personality, represents tenacity, strength and courage.\nWhat are you waiting for to schedule with us at @cubatattoostudio and wear a unique design on your skin?\n\n#Zeus #Tatoo #GriegoTattoo #ZeusTattoo #BlackAndGreyTattoo #ColorTattoo #realismo",
      "permalink": "https://www.instagram.com/p/DNdxWEKJOAf/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3696698460942788261",
      "imageUrl": img_karli_03,
      "caption": "Caerán a tu lado mil, y diez mil a tu diestra;\nMas a ti no llegará…\n\nThis piece speaks louder than words.\nWhat does your faith mean to you?\n\nDone at @cubatattoostudio \nBook your session today and wear your story forever.\nDM me to book\n#JesusTattoo #TatuajeReligioso #RealismoTatuaje #BlackAndGreyTattoo #InkedFaith #TatuajesDeFe #TatuadoresLatinos\n#CubaTattooStudio #TattooArt #InkedAndBlessed #ChristianTattoo #Tattoolnspiration\n#TatuajesRealistas #TatuajesReligiosos #FeEnLaPiel\n#InkedStory #InstaTattoo #TattooOfTheDay #TattooLovers",
      "permalink": "https://www.instagram.com/p/DNNT6oOOmal/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3843597864592770207",
      "imageUrl": img_karli_04,
      "caption": "100% healed tattoo ✨\n\nThis is what a piece looks like when the process is respected and the instructions for subsequent care are correctly followed. The final result depends not only on the artist, but also on the customer’s commitment during healing.\n\nLittle reminder: aftercare is as important as the tattoo itself.",
      "permalink": "https://www.instagram.com/p/DVXM-TCgISf/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3838299624435645824",
      "imageUrl": img_karli_05,
      "caption": "Custom piece created in honor of his son💙\n\nA meaningful design combining his favorite heroes and birth details, turning a special memory into lasting art.",
      "permalink": "https://www.instagram.com/p/DVEYSwYAH2A/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3837664108150394847",
      "imageUrl": img_karli_06,
      "caption": "The Death Card\n\n100% personalized and completely hand-drawn design for this client.\n\nEach detail was created from scratch to achieve a unique piece, with a balance between strength and delicacy in black & gray.\n\nThank you for trusting my art\n\nWho signs up for an exclusive piece?",
      "permalink": "https://www.instagram.com/p/DVCHyxtkg_f/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3826011183758038495",
      "imageUrl": img_karli_07,
      "caption": "Cute floral design with a lot of meaning and intention🫶🏻\n#mandalatattoo #floraltattoo #floralmandala #dotwork #albuquerquetattoo",
      "permalink": "https://www.instagram.com/p/DUYuOaKkdXf/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3813711965362239146",
      "imageUrl": img_karli_08,
      "caption": "Covering unwanted tattoos🤭\n\nLeoness in realism, symbol of strength, protection and elegance 🖤\n\nBooks open for new tattoos and personalized projects.\n\n#LionessTattoo\n#RealismTattoo\n#BlackAndGreyTattoo\n#TattooArt\n#AgendaAbierta",
      "permalink": "https://www.instagram.com/p/DTtBtObEraq/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3806659418985073779",
      "imageUrl": img_karli_09,
      "caption": "Un retrato lleno de amor y elegancia 🐶👑\nTatuaje realista de Millie, una reina de cuatro patas que ahora acompaña a su humana para siempre en la piel.\nCada detalle fue pensado para honrar su personalidad y el vínculo tan especial que comparten. 💖\n#cubatattoostudio #albuquerquetattoo #realismtattoo #pettattoo #dogtattooportrait",
      "permalink": "https://www.instagram.com/p/DTT-JKxgAxz/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3802359785584619414",
      "imageUrl": img_karli_10,
      "caption": "Andrea loves eye and floral designs, and at Cuba Tattoo Studio we always make sure to deliver what our clients love 👁️\n\n📖 Now booking.\n\n#tattoo #eyetattoo #floraltattoo #blackandgreytattoo #cubatattoostudio",
      "permalink": "https://www.instagram.com/p/DTEshRIAG-W/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3799353092672114070",
      "imageUrl": img_karli_11,
      "caption": "Delicate tattoos, fine lines and meanings that grow on time 🌿\n\nBeauty is in the simple.\n\n📖 Books open\n\nDM for appointments and personalized designs.\n\n#finelinetattoo #floraltattoo #botanicaltattoo #blackworktattoo\n#tattooartist",
      "permalink": "https://www.instagram.com/p/DS6A4IJAM2W/",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "3797262779660934364",
      "imageUrl": img_karli_12,
      "caption": "At first glance, some tiny peaches 🍑\n\nBut behind a tattoo that seems insignificant, huge stories are hidden.\n\nThis tattoo speaks of bows.\n\nOf shared memories, of roots, of love that matures with time.\n\nBecause sometimes, the most delicate thing is what weighs the most on the heart.\n\nThank you for entrusting me with something so intimate.\n\nSmall tattoos also tell giant stories ✨\n\n📖💉 Open agenda - write to me to create something with meaning, even if it is the size of a sigh.\n\n#TatuajeConSignificado\n#TatuajeHermanos\n#TatuajesPequeños\n#FineLineTattoo\n#colortattoos",
      "permalink": "https://www.instagram.com/p/DSylmEcgJzc/",
      "artist": "karli",
      "isLocal": true
    }
  ],
  "studio": {
    "profile": null,
    "posts": [
      {
        "id": "3765029695869102410",
        "imageUrl": img_studio_01,
        "caption": "Some tattoos are more than designs — they’re balance, energy, and connection.\nMandalas remind me that every detail has a purpose. 🌿  If you have thought about getting one, maybe this is your sign ✨\n\n#mandalatattoo #dotworktattoo #ornamentaltattoo #goodnina #ninaromeroink #tattooart #tattooartist #blackwork #artonthebody #tattoolover #tatuadora",
        "permalink": "https://www.instagram.com/p/DRAEo93EylK/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3790511475068585170",
        "imageUrl": img_studio_02,
        "caption": "Every color, every shadow, and every choice in this design has intention behind it.\nThis is more than a tattoo — it’s a story built on skin, with emotion, strength, and depth.\nPieces like this are born from trust, communication, and a clear artistic vision from the very first line.\n\nIf you have a unique idea and want to turn it into real art, now is the time.\n📩 Book your appointment and let’s create something made just for you.\n\n📍 @cubatattoostudio \n#tattoo #tattooartistmagazine #tattoofullcolor #tatuaje #abq",
        "permalink": "https://www.instagram.com/p/DSamhqEgUTS/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3701331489341104159",
        "imageUrl": img_studio_03,
        "caption": "Un diseño poderoso, lleno de personalidad, representa tenacidad, fuerza y valor.\nQué esperas para agendar con nosotros en @cubatattoostudio y llevar en tu piel un diseño único? \n\nA powerful design, full of personality, represents tenacity, strength and courage.\nWhat are you waiting for to schedule with us at @cubatattoostudio and wear a unique design on your skin?\n\n#Zeus #Tatoo #GriegoTattoo #ZeusTattoo #BlackAndGreyTattoo #ColorTattoo #realismo",
        "permalink": "https://www.instagram.com/p/DNdxWEKJOAf/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3846971193186746126",
        "imageUrl": img_studio_04,
        "caption": "Cover up 🌸\nAn old tattoo turned into something completely new.\nNow the question is… can you spot where the old tattoo was",
        "permalink": "https://www.instagram.com/p/DVjL-sHDn8O/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3846249838657229611",
        "imageUrl": img_studio_05,
        "caption": "🔥First session done. This powerful piece is just getting started. More to come\nBooking large scale projects. DM for appointments.",
        "permalink": "https://www.instagram.com/p/DVgn9mWkVMr/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3845819489375500307",
        "imageUrl": img_studio_06,
        "caption": "Small cover-up ✨\n\nSometimes all it takes is a little color to transform something that no longer represents you.\nThis was a small cover-up turned into a vibrant piece. 🎨\n\nMy books are open! If you have a tattoo you’d like to cover with something bold and colorful, feel free to send me a DM and we can talk about a design for you.\n\n📍 Albuquerque, NM\n\n#cubatattoostudio #colortattoo #fullcolortattoo #colortatooartist #coveruptattoo",
        "permalink": "https://www.instagram.com/p/DVfGHMWgDgT/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3845520958757278416",
        "imageUrl": img_studio_07,
        "caption": "In Mexican culture, many people believe in La Santa Muerte as a symbol of protection, faith, and guidance. This piece represents that devotion, mixed with time, luck, and life’s journey. 🖤⏳♠️",
        "permalink": "https://www.instagram.com/p/DVeCPADDBLQ/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3843656155277417588",
        "imageUrl": img_studio_08,
        "caption": "Although this piece steps a bit outside of my usual style, I truly enjoyed working on it.\nIt’s also part of the 30% off promotion we’re currently offering 🔥\n\nIf you’re thinking about something similar, now’s the time to take advantage.",
        "permalink": "https://www.instagram.com/p/DVXaOieDdx0/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3843597864592770207",
        "imageUrl": img_studio_09,
        "caption": "100% healed tattoo ✨\n\nThis is what a piece looks like when the process is respected and the instructions for subsequent care are correctly followed. The final result depends not only on the artist, but also on the customer’s commitment during healing.\n\nLittle reminder: aftercare is as important as the tattoo itself.",
        "permalink": "https://www.instagram.com/p/DVXM-TCgISf/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3842622245525633256",
        "imageUrl": img_studio_10,
        "caption": "Another powerful piece done under the 30% OFF Religious Tattoo Promotion 🙏\n\nMarch booking is officially open and the promo is still running.\nIf you’re planning something meaningful, now is the perfect time to start.\n\nLimited availability for March — lock in your spot before it’s gone.",
        "permalink": "https://www.instagram.com/p/DVTvJK-kbjo/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3841968206478686450",
        "imageUrl": img_studio_11,
        "caption": "Another piece from our extended March promotion 🔥\nEnjoy 30% OFF on religious tattoos all month long.\n\nMarch spots are filling fast — secure yours now and let’s bring your vision to life.\n\nBook your session before the remaining dates are gone.",
        "permalink": "https://www.instagram.com/p/DVRabppgbjy/",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "3841239444540546245",
        "imageUrl": img_studio_12,
        "caption": "Because so many people missed out this month, we’ve decided to extend our 30% OFF promotion on religious themed pieces through March 🙏\n\nFaith-inspired projects like this one are now eligible for the discount — giving more of you the chance to bring meaningful art to life.\n\nIf you were thinking about getting something spiritual done, this is your opportunity before spots fill again.\n\nLet me know what you’ve been wanting to create ✨",
        "permalink": "https://www.instagram.com/p/DVO0uxNDtzF/",
        "artist": "studio",
        "isLocal": true
      }
    ]
  },
  "artists": {
    "david": {
      "profile": {
        "username": "david_guzman_tattoo",
        "fullName": "David Guzman Claveria",
        "profilePicUrl": "https://instagram.fdyu1-1.fna.fbcdn.net/v/t51.2885-19/483495480_981029390787250_8713488228778299054_n.jpg?stp=dst-jpg_s150x150_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLmRqYW5nby4xMDgwLmMyIn0&_nc_ht=instagram.fdyu1-1.fna.fbcdn.net&_nc_cat=110&_nc_oc=Q6cZ2QG4hS61od3xLw2si2mpfObNyLtmqwIKnH2SSeAprcSUvCnN_82VX4RrNSkxGuKfDdA&_nc_ohc=zj8gJxtkK58Q7kNvwG8WDC5&_nc_gid=GHqauHQYE3xs5GI4-J_puA&edm=AP4sbd4BAAAA&ccb=7-5&oh=00_AfzH53sHouWmHjKsjIXWsKt8iZWlvqgzIGVXFW6SMm-6Vw&oe=69B0F138&_nc_sid=7a9f4b",
        "localProfilePic": profile_david
      },
      "posts": [
        {
          "id": "3790511475068585170",
          "imageUrl": img_david_01,
          "caption": "Every color, every shadow, and every choice in this design has intention behind it.\nThis is more than a tattoo — it’s a story built on skin, with emotion, strength, and depth.\nPieces like this are born from trust, communication, and a clear artistic vision from the very first line.\n\nIf you have a unique idea and want to turn it into real art, now is the time.\n📩 Book your appointment and let’s create something made just for you.\n\n📍 @cubatattoostudio \n#tattoo #tattooartistmagazine #tattoofullcolor #tatuaje #abq",
          "permalink": "https://www.instagram.com/p/DSamhqEgUTS/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3752195299918071455",
          "imageUrl": img_david_02,
          "caption": "✨ Surreal Neon Vision ✨\n Work in progress 📌\nA bold mix of surrealism and futuristic realism, bringing this character to life through powerful neons, soft blends and dramatic contrasts.\nEvery detail is custom, every stroke has intention — art that lives on your skin.\n\nIf you want a unique surreal piece with this level of depth and color, I’m now booking new sessions. 🚀🖌️\n\n📍 @cubatattoostudio – Albuquerque, NM\n📲 DM to book your appointment\n\n#CubaTattooStudio #SurrealTattoo #ColorRealism #NeonTattoo #LegTattoo #TattooArtist #CustomTattoo #TattooArt #Inked #BookNow #RealisticTattoo #Colortattoo #SurrealismArt",
          "permalink": "https://www.instagram.com/p/DQSeb7Lgcaf/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3676888274027693491",
          "imageUrl": img_david_03,
          "caption": "🔥 Winner of “Best of Show - Color” at @newmexicotattoofiesta 2025 🔥\nThis piece was completed in just 9 hours — packed with texture, contrast, color, and soul.\nHuge thanks to everyone who supported me, and a special shoutout to @_poor_vida_ for the help and for giving us the chance to be part of this amazing event.\n\nThis is what we do at @cubatattoostudio — high-level art with full dedication.\nWe’re just getting started. Let’s keep raising the bar! 💪🏽🖤\n\n📍CUBA TATTOO STUDIO | Albuquerque, NM\n📅 Book your session now and bring your vision to life.\n\n#BestOfShow #TattooFiesta2025 #ColorTattoo #RealismTattoo #CubaTattooStudio #PoorVida #NewMexicoTattoos #TattooAward #TattooArtist #9HourTattoo #FullColorTattoo #TattooInspiration #AlbuquerqueTattoo #TattooLife",
          "permalink": "https://www.instagram.com/p/DMG7md8OEWz/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3846971193186746126",
          "imageUrl": img_david_04,
          "caption": "Cover up 🌸\nAn old tattoo turned into something completely new.\nNow the question is… can you spot where the old tattoo was",
          "permalink": "https://www.instagram.com/p/DVjL-sHDn8O/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3846249838657229611",
          "imageUrl": img_david_05,
          "caption": "🔥First session done. This powerful piece is just getting started. More to come\nBooking large scale projects. DM for appointments.",
          "permalink": "https://www.instagram.com/p/DVgn9mWkVMr/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3845520958757278416",
          "imageUrl": img_david_06,
          "caption": "In Mexican culture, many people believe in La Santa Muerte as a symbol of protection, faith, and guidance. This piece represents that devotion, mixed with time, luck, and life’s journey. 🖤⏳♠️",
          "permalink": "https://www.instagram.com/p/DVeCPADDBLQ/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3843656155277417588",
          "imageUrl": img_david_07,
          "caption": "Although this piece steps a bit outside of my usual style, I truly enjoyed working on it.\nIt’s also part of the 30% off promotion we’re currently offering 🔥\n\nIf you’re thinking about something similar, now’s the time to take advantage.",
          "permalink": "https://www.instagram.com/p/DVXaOieDdx0/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3842622245525633256",
          "imageUrl": img_david_08,
          "caption": "Another powerful piece done under the 30% OFF Religious Tattoo Promotion 🙏\n\nMarch booking is officially open and the promo is still running.\nIf you’re planning something meaningful, now is the perfect time to start.\n\nLimited availability for March — lock in your spot before it’s gone.",
          "permalink": "https://www.instagram.com/p/DVTvJK-kbjo/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3841968206478686450",
          "imageUrl": img_david_09,
          "caption": "Another piece from our extended March promotion 🔥\nEnjoy 30% OFF on religious tattoos all month long.\n\nMarch spots are filling fast — secure yours now and let’s bring your vision to life.\n\nBook your session before the remaining dates are gone.",
          "permalink": "https://www.instagram.com/p/DVRabppgbjy/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3841239444540546245",
          "imageUrl": img_david_10,
          "caption": "Because so many people missed out this month, we’ve decided to extend our 30% OFF promotion on religious themed pieces through March 🙏\n\nFaith-inspired projects like this one are now eligible for the discount — giving more of you the chance to bring meaningful art to life.\n\nIf you were thinking about getting something spiritual done, this is your opportunity before spots fill again.\n\nLet me know what you’ve been wanting to create ✨",
          "permalink": "https://www.instagram.com/p/DVO0uxNDtzF/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3840502269272484934",
          "imageUrl": img_david_11,
          "caption": "Faith, family, and purpose. 🙏\nThis piece is part of our 30% OFF promotion on religious-themed tattoos for this month.\n\nIf you’ve been thinking about representing your faith through art, this is the perfect time to make it happen.\n\n📍 @cubatattoostudio – Albuquerque, NM\n📩 Send us a DM to book your appointment before spots fill up.",
          "permalink": "https://www.instagram.com/p/DVMNHdPEWxG/",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "3839844037859327047",
          "imageUrl": img_david_12,
          "caption": "Faith turned into art ✝️🔥\nThis piece was part of our 30% OFF religious tattoo promotion this month.\nAll spots are now filled — but if you want me to continue this promotion next month, drop a comment below 👇",
          "permalink": "https://www.instagram.com/p/DVJ3c7dgbxH/",
          "artist": "david",
          "isLocal": true
        }
      ]
    },
    "nina": {
      "profile": {
        "username": "goodnina_tattooing",
        "fullName": "Jaline Romero Heredia",
        "profilePicUrl": "https://scontent-iev1-1.cdninstagram.com/v/t51.82787-15/628057936_18068955278621963_8951441152345468659_n.jpg?stp=dst-jpg_s150x150_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLmRqYW5nby42MzcuYzIifQ&_nc_ht=scontent-iev1-1.cdninstagram.com&_nc_cat=111&_nc_oc=Q6cZ2QH34TR4vNuoknAF-PftCEFVoyYwvHe9W6Gw3F-VCzkmY91D3fHfdkj4ky7P9JoLwDk&_nc_ohc=A5vBUjOdNZsQ7kNvwHu989W&_nc_gid=YwInctwKIybHeLHLXRyj9w&edm=AP4sbd4BAAAA&ccb=7-5&oh=00_Afz_c79SgUlaeaCuIMmEqEN-xYWtxys9dt34aqu0wyEV_w&oe=69B0E2D8&_nc_sid=7a9f4b",
        "localProfilePic": profile_nina
      },
      "posts": [
        {
          "id": "3789748958915404471",
          "imageUrl": img_nina_01,
          "caption": "Soft art for timeless skin 🌸\nFine line floral tattoo, created with intention and detail.\nSubtle, feminine, and meant to flow with the body.  By: @goodnina_tattooing  #abqtattooartist #abqtattoos #finelinetattoos #floraltattoo #tattoogi̇rl #newmexicotattoo #goodnina #tattoolover",
          "permalink": "https://www.instagram.com/p/DSX5JlkDyK3/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3780998917119924705",
          "imageUrl": img_nina_02,
          "caption": "Si te gustan las líneas finas, la simetría y los detalles elegantes, este estilo es perfecto para ti.\nEstoy abriendo agenda para más piezas como esta: personalizadas, delicadas y hechas a tu medida.\n\n💬 Envíame mensaje para cotizar tu diseño\n🖤 Trabajos limpios · Trazo fino · Estilo ornamental único  #tattooing #tattoo #tattooartists #tattoogirl #tattooornamental #geometrico #tattoolifestyle #tattooidea #tattooabq #tattooalburquerque #tattoonewmexico #tattooshop #tattoolover #tattoowork #goodnina",
          "permalink": "https://www.instagram.com/p/DR4znuHEdnh/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3844075245544772395",
          "imageUrl": img_nina_03,
          "caption": "A new chapter in red.\n\nThreads of Spring is now available throughout March.\nLimited booking spots each week.\n\nDM to claim your piece.\n#finelinetattoos #abqtattoos #femaletattoo #ornamentaltattoos #tattoo",
          "permalink": "https://www.instagram.com/p/DVY5hGskZMr/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3843307420081266953",
          "imageUrl": img_nina_04,
          "caption": "Tiny tattoos that stole my heart in February\n| love when something this small can hold so much meaning.\nDelicate lines, soft shading, tiny details... but big intention.\nFebruary was full of subtle pieces that whisper instead of scream tr\nAnd honestly? Those are my favorite kind.\nGracias por confiar en mí para llevar algo tan personal en la piel.\nMis tiny siempre tendrán un lugar especial.\nIf you’re thinking about a tiny piece... this is your sign.\n- Good Nina\n#tynitattoo #alburquerque #finelinetattoos #feminetattoo #newméxico",
          "permalink": "https://www.instagram.com/p/DVWK7xgkSEJ/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3841975692388548873",
          "imageUrl": img_nina_05,
          "caption": "Este diseño nació para fluir con el cuerpo.\nNo es solo un tatuaje, es una pieza que respira con cada curva. ⚜️\nEl tamaño puede adaptarse según zona.\nSi conectas con esta pieza, escríbeme para reservar.✨ #feminitattoo #ornamentaltattoo #abqtattooartist #newmex",
          "permalink": "https://www.instagram.com/p/DVRcIlcgUEJ/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3841153399509836708",
          "imageUrl": img_nina_06,
          "caption": "Flores de Febrero.  Creando un jardín. #tattooflowers #linetattoos #abq #abqtattooartist #tattoogirl",
          "permalink": "https://www.instagram.com/p/DVOhKphkWOk/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3837115455220334381",
          "imageUrl": img_nina_07,
          "caption": "Líneas que fluyen como energía.\nMandala en pura línea, trabajado con intención y precisión.\n\nAgenda abierta ✨\n#MandalaTattoo #LineworkTattoo #FineLineTattoo #CustomTattoo #TattooArtist",
          "permalink": "https://www.instagram.com/p/DVALC02kb8t/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3834861432593126195",
          "imageUrl": img_nina_08,
          "caption": "Este tatuaje es un recordatorio de cómo la magia sucede. In God’s Hands, las sorpresas son parte del camino. ❤️✨. #tattoo #abqtattoo #tattooartists #tattooidea #newmexicoart",
          "permalink": "https://www.instagram.com/p/DU4KiesjxMz/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3830274259437032141",
          "imageUrl": img_nina_09,
          "caption": "“Un mes después 🤍✨\nRetoque en el nombre y el resto del tatuaje ya curado.\nGracias por volver y confiar otra vez 🐾\nNada más lindo que ver cómo sana un tattoo con el tiempo.” #petlovers #petstattoo #abqtattoo #newméxico",
          "permalink": "https://www.instagram.com/p/DUn3iUyERLN/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3827683857697691570",
          "imageUrl": img_nina_10,
          "caption": "Hoy pasó algo muy especial ✨\nMi clienta confió en mí, en un dibujo que traía en mi libreta, y me dejó fluir en freehand.\nEl proceso fue intuitivo, orgánico… y el resultado nos enamoró a las dos.\nGracias @grisellgandarilla por confiar, así nacen los tatuajes con alma 🖤 #tattoo #fineline #escorpio♏️ #abqtattoo #tattooartists",
          "permalink": "https://www.instagram.com/p/DUeqjBKkVey/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3824716028602095130",
          "imageUrl": img_nina_11,
          "caption": "Recuerden que este viernes 13 de febrero tenemos ofertas especiales ✨\nPara solteros, parejas, novios, amigos, familia…\ny para todo el que sienta amor 🖤\nPorque el amor también se tatúa. #tattoo #finelinetattoos #tattooabq #tattooartist #valentinday❤️",
          "permalink": "https://www.instagram.com/p/DUUHva7khYa/",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "3823333901162526007",
          "imageUrl": img_nina_12,
          "caption": "Plot twist: el tatuaje no fue el protagonista…\nEllas frente a la cámara: 💃📸😂",
          "permalink": "https://www.instagram.com/p/DUPNe0cgDU3/",
          "artist": "nina",
          "isLocal": true
        }
      ]
    },
    "karli": {
      "profile": {
        "username": "karlii_castillo_tattoos",
        "fullName": "Karlii Castillo",
        "profilePicUrl": "https://instagram.fbkk5-6.fna.fbcdn.net/v/t51.82787-15/515130174_17954476451963545_5881486759012822711_n.jpg?stp=dst-jpg_s150x150_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLmRqYW5nby45ODcuYzIifQ&_nc_ht=instagram.fbkk5-6.fna.fbcdn.net&_nc_cat=101&_nc_oc=Q6cZ2QGuvKrX8oNu-JH_Mtpw2pBKvudbYRYUWDkgGFs9AAJAus0oK8StcyHLiIHuLefxp5FGWzUc_UBmcJWePBqyHubn&_nc_ohc=kr-EYwKn_2EQ7kNvwGOGujk&_nc_gid=hiQmDAJlVRzvjXj-DmYTiQ&edm=AP4sbd4BAAAA&ccb=7-5&oh=00_AfwUpgjOUoD_am3OzYK8fvGjcjkCXhPIh4vZfQ44sKRIig&oe=69B0F951&_nc_sid=7a9f4b",
        "localProfilePic": profile_karli
      },
      "posts": [
        {
          "id": "3762976379093203995",
          "imageUrl": img_karli_01,
          "caption": "Details, depth and a hypnotizing look. This tattoo was worked to create a piece with visual strength from any angle, soft shading, marked textures and those incandescent tones that give it life.\n\nBooks open for custom designs like this.\n\nIf you want something unique, made for you, send me a DM and we’ll plan it.\n\nTatuado por: Karlii Castillo\n📍 Cuba Tattoo Studio – Albuquerque, NM\n\n#AgendaAbierta #CubaTattooStudio #AlbuquerqueTattoo #AlbuquerqueArtist #TattooABQ #Realismo #RealismTattoo #BlackAndGreyTattoo #DarkArtTattoo #InkLife #TattooCollector #TatuajesFineline #TatuajeRealista #CustomTattoo #SkinArt #TattooStudio #BookNow #TattooDesign #MedusaTattoo",
          "permalink": "https://www.instagram.com/p/DQ4xxRmCTwb/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3701331489341104159",
          "imageUrl": img_karli_02,
          "caption": "Un diseño poderoso, lleno de personalidad, representa tenacidad, fuerza y valor.\nQué esperas para agendar con nosotros en @cubatattoostudio y llevar en tu piel un diseño único? \n\nA powerful design, full of personality, represents tenacity, strength and courage.\nWhat are you waiting for to schedule with us at @cubatattoostudio and wear a unique design on your skin?\n\n#Zeus #Tatoo #GriegoTattoo #ZeusTattoo #BlackAndGreyTattoo #ColorTattoo #realismo",
          "permalink": "https://www.instagram.com/p/DNdxWEKJOAf/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3696698460942788261",
          "imageUrl": img_karli_03,
          "caption": "Caerán a tu lado mil, y diez mil a tu diestra;\nMas a ti no llegará…\n\nThis piece speaks louder than words.\nWhat does your faith mean to you?\n\nDone at @cubatattoostudio \nBook your session today and wear your story forever.\nDM me to book\n#JesusTattoo #TatuajeReligioso #RealismoTatuaje #BlackAndGreyTattoo #InkedFaith #TatuajesDeFe #TatuadoresLatinos\n#CubaTattooStudio #TattooArt #InkedAndBlessed #ChristianTattoo #Tattoolnspiration\n#TatuajesRealistas #TatuajesReligiosos #FeEnLaPiel\n#InkedStory #InstaTattoo #TattooOfTheDay #TattooLovers",
          "permalink": "https://www.instagram.com/p/DNNT6oOOmal/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3843597864592770207",
          "imageUrl": img_karli_04,
          "caption": "100% healed tattoo ✨\n\nThis is what a piece looks like when the process is respected and the instructions for subsequent care are correctly followed. The final result depends not only on the artist, but also on the customer’s commitment during healing.\n\nLittle reminder: aftercare is as important as the tattoo itself.",
          "permalink": "https://www.instagram.com/p/DVXM-TCgISf/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3838299624435645824",
          "imageUrl": img_karli_05,
          "caption": "Custom piece created in honor of his son💙\n\nA meaningful design combining his favorite heroes and birth details, turning a special memory into lasting art.",
          "permalink": "https://www.instagram.com/p/DVEYSwYAH2A/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3837664108150394847",
          "imageUrl": img_karli_06,
          "caption": "The Death Card\n\n100% personalized and completely hand-drawn design for this client.\n\nEach detail was created from scratch to achieve a unique piece, with a balance between strength and delicacy in black & gray.\n\nThank you for trusting my art\n\nWho signs up for an exclusive piece?",
          "permalink": "https://www.instagram.com/p/DVCHyxtkg_f/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3826011183758038495",
          "imageUrl": img_karli_07,
          "caption": "Cute floral design with a lot of meaning and intention🫶🏻\n#mandalatattoo #floraltattoo #floralmandala #dotwork #albuquerquetattoo",
          "permalink": "https://www.instagram.com/p/DUYuOaKkdXf/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3813711965362239146",
          "imageUrl": img_karli_08,
          "caption": "Covering unwanted tattoos🤭\n\nLeoness in realism, symbol of strength, protection and elegance 🖤\n\nBooks open for new tattoos and personalized projects.\n\n#LionessTattoo\n#RealismTattoo\n#BlackAndGreyTattoo\n#TattooArt\n#AgendaAbierta",
          "permalink": "https://www.instagram.com/p/DTtBtObEraq/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3806659418985073779",
          "imageUrl": img_karli_09,
          "caption": "Un retrato lleno de amor y elegancia 🐶👑\nTatuaje realista de Millie, una reina de cuatro patas que ahora acompaña a su humana para siempre en la piel.\nCada detalle fue pensado para honrar su personalidad y el vínculo tan especial que comparten. 💖\n#cubatattoostudio #albuquerquetattoo #realismtattoo #pettattoo #dogtattooportrait",
          "permalink": "https://www.instagram.com/p/DTT-JKxgAxz/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3802359785584619414",
          "imageUrl": img_karli_10,
          "caption": "Andrea loves eye and floral designs, and at Cuba Tattoo Studio we always make sure to deliver what our clients love 👁️\n\n📖 Now booking.\n\n#tattoo #eyetattoo #floraltattoo #blackandgreytattoo #cubatattoostudio",
          "permalink": "https://www.instagram.com/p/DTEshRIAG-W/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3799353092672114070",
          "imageUrl": img_karli_11,
          "caption": "Delicate tattoos, fine lines and meanings that grow on time 🌿\n\nBeauty is in the simple.\n\n📖 Books open\n\nDM for appointments and personalized designs.\n\n#finelinetattoo #floraltattoo #botanicaltattoo #blackworktattoo\n#tattooartist",
          "permalink": "https://www.instagram.com/p/DS6A4IJAM2W/",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "3797262779660934364",
          "imageUrl": img_karli_12,
          "caption": "At first glance, some tiny peaches 🍑\n\nBut behind a tattoo that seems insignificant, huge stories are hidden.\n\nThis tattoo speaks of bows.\n\nOf shared memories, of roots, of love that matures with time.\n\nBecause sometimes, the most delicate thing is what weighs the most on the heart.\n\nThank you for entrusting me with something so intimate.\n\nSmall tattoos also tell giant stories ✨\n\n📖💉 Open agenda - write to me to create something with meaning, even if it is the size of a sigh.\n\n#TatuajeConSignificado\n#TatuajeHermanos\n#TatuajesPequeños\n#FineLineTattoo\n#colortattoos",
          "permalink": "https://www.instagram.com/p/DSylmEcgJzc/",
          "artist": "karli",
          "isLocal": true
        }
      ]
    }
  },
  "lastFetched": "2026-03-06T18:34:35.856Z"
};

export default instagramData;
