// @ts-nocheck
// This file is auto-generated by scripts/fetch-insta.js
// Do not edit manually

import img_studio_01 from '../assets/gallery/studio/01.jpg';
import img_studio_02 from '../assets/gallery/studio/02.jpg';
import img_david_01 from '../assets/gallery/david/01.jpg';
import img_david_02 from '../assets/gallery/david/02.jpg';
import img_david_03 from '../assets/gallery/david/03.jpg';
import img_david_04 from '../assets/gallery/david/04.jpg';
import profile_david from '../assets/artists/david.jpg';
import img_nina_01 from '../assets/gallery/nina/01.jpg';
import img_nina_02 from '../assets/gallery/nina/02.jpg';
import img_nina_03 from '../assets/gallery/nina/03.jpg';
import img_nina_04 from '../assets/gallery/nina/04.jpg';
import profile_nina from '../assets/artists/nina.jpg';
import img_karli_01 from '../assets/gallery/karli/01.jpg';
import img_karli_02 from '../assets/gallery/karli/02.jpg';
import profile_karli from '../assets/artists/karli.jpg';

export interface Post {
  id: string;
  imageUrl: ImageMetadata | string;
  caption?: string;
  permalink?: string;
  artist?: string;
  isLocal?: boolean;
}

export interface ArtistData {
  profile: {
    username?: string;
    fullName?: string;
    localProfilePic?: ImageMetadata | string;
  } | null;
  posts: Post[];
}

export interface InstagramData {
  posts: Post[];
  studio?: { profile: ArtistData['profile']; posts: Post[] };
  artists?: Record<string, ArtistData>;
  lastFetched?: string;
}

const instagramData: InstagramData = {
  "posts": [
    {
      "id": "local-studio-0",
      "imageUrl": img_studio_01,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "local-studio-1",
      "imageUrl": img_studio_02,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "studio",
      "isLocal": true
    },
    {
      "id": "local-david-0",
      "imageUrl": img_david_01,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-1",
      "imageUrl": img_david_02,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-2",
      "imageUrl": img_david_03,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-david-3",
      "imageUrl": img_david_04,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "david",
      "isLocal": true
    },
    {
      "id": "local-nina-0",
      "imageUrl": img_nina_01,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-1",
      "imageUrl": img_nina_02,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-2",
      "imageUrl": img_nina_03,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-nina-3",
      "imageUrl": img_nina_04,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "nina",
      "isLocal": true
    },
    {
      "id": "local-karli-0",
      "imageUrl": img_karli_01,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    },
    {
      "id": "local-karli-1",
      "imageUrl": img_karli_02,
      "caption": "Local fallback image",
      "permalink": "",
      "artist": "karli",
      "isLocal": true
    }
  ],
  "studio": {
    "profile": null,
    "posts": [
      {
        "id": "local-studio-0",
        "imageUrl": img_studio_01,
        "caption": "Local fallback image",
        "permalink": "",
        "artist": "studio",
        "isLocal": true
      },
      {
        "id": "local-studio-1",
        "imageUrl": img_studio_02,
        "caption": "Local fallback image",
        "permalink": "",
        "artist": "studio",
        "isLocal": true
      }
    ]
  },
  "artists": {
    "david": {
      "profile": {
        "username": "david_fallback",
        "fullName": "david Fallback",
        "localProfilePic": profile_david
      },
      "posts": [
        {
          "id": "local-david-0",
          "imageUrl": img_david_01,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-1",
          "imageUrl": img_david_02,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-2",
          "imageUrl": img_david_03,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        },
        {
          "id": "local-david-3",
          "imageUrl": img_david_04,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "david",
          "isLocal": true
        }
      ]
    },
    "nina": {
      "profile": {
        "username": "nina_fallback",
        "fullName": "nina Fallback",
        "localProfilePic": profile_nina
      },
      "posts": [
        {
          "id": "local-nina-0",
          "imageUrl": img_nina_01,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-1",
          "imageUrl": img_nina_02,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-2",
          "imageUrl": img_nina_03,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        },
        {
          "id": "local-nina-3",
          "imageUrl": img_nina_04,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "nina",
          "isLocal": true
        }
      ]
    },
    "karli": {
      "profile": {
        "username": "karli_fallback",
        "fullName": "karli Fallback",
        "localProfilePic": profile_karli
      },
      "posts": [
        {
          "id": "local-karli-0",
          "imageUrl": img_karli_01,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        },
        {
          "id": "local-karli-1",
          "imageUrl": img_karli_02,
          "caption": "Local fallback image",
          "permalink": "",
          "artist": "karli",
          "isLocal": true
        }
      ]
    }
  },
  "lastFetched": "2026-02-13T01:54:07.363Z"
};

export default instagramData;
