name: Link Checker

on: [push, pull_request]

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose docs/**/*.md
